export const ADD_ARTICLE = "ADD_ARTICLE"
export const ALL_ROOMS = "ALL_ROOMS"
export const API_ERRORED = "API_ERRORED"
export const CONTACT_US = "CONTACT_US"
export const DATA_LOADED = "DATA_LOADED"
export const DATA_REQUESTED = "DATA_REQUESTED"
export const FOUND_BAD_WORD = "FOUND_BAD_WORD"
export const LOAD_POST = "LOAD_POST"