export const ADD_ARTICLE = "ADD_ARTICLE"
export const CONTACT_US = "CONTACT_US"
export const LOAD_POST = "LOAD_POST"
export const ALL_ROOMS = "ALL_ROOMS"
export const FOUND_BAD_WORD = "FOUND_BAD_WORD"